apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtestobjects.test.haarchri.io
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "disabled"
spec:
  metadata:
    annotations:
      # When we add this annotation here, the CRDs will receive this annotation.
      kustomize.toolkit.fluxcd.io/prune: "disabled"
  group: test.haarchri.io
  names:
    kind: XTestObject
    plural: xtestobjects
  claimNames:
    kind: TestObject
    plural: testobjects
  versions:
  - name: v1
    referenceable: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: "The OpenAPIV3Schema of this Composite Resource Definition."
            properties:
              example-trigger:
                type: string
            required:
              - example-trigger
